### ISSUE TITLE
Why use 'Pr(y=1) = 1/(1+exp(-2F(x)))' instead of 'Pr(y=1) = 1/(1+exp(-F(x)))'?

### ISSUE THREAD

**Issue by liudragonfly** [qiyiping/gbdt#2]
Functions for gradient boosting classifier make me confused.
1. Why use 'Pr(y=1) = 1/(1+exp(-2F(x)))' instead of 'Pr(y=1) = 1/(1+exp(-F(x)))'?
2. Why use 'L(y, F(x)) = log(1+2exp(-2yF(x)))' instead of L(y, F(x)) = log(1+exp(-yF(x)))'
Thank you.

**Comment by qiyiping** [comment]
hi,
It's ok to use 'Pr(y=1) = 1/(1+exp(-F(x)))' and change the loss/gradient accordingly.
My implementation followed the definition in Friedman's paper.

thanks,
yiping

**Comment by liudragonfly** [comment]
Thank you very much. 谢谢。
