### ISSUE TITLE
get impurity question

### ISSUE THREAD

**Issue by PseudoProgrammer** [qiyiping/gbdt#6]
计算基尼不纯度，代码里的逻辑是这样的，见fitness.cpp代码：

162   for (size_t j = unknown; j < len-1; ++j) {
163     s = data_copy[j]->target * data_copy[j]->weight;
164     ss = Squared(data_copy[j]->target) * data_copy[j]->weight;
165     c = data_copy[j]->weight;
166
167     ls += s;
168     lss += ss;
169     lc += c;
170
171     rs -= s;
172     rss -= ss;
173     rc -= c;
174
175     ValueType f1 = data_copy[j]->feature[index];
176     ValueType f2 = data_copy[j+1]->feature[index];
177     if (AlmostEqual(f1, f2))
178       continue;
179
180     fitness1 = lc > 1? (lss - ls*ls/lc) : 0;
181     if (fitness1 < 0) {
182       // std::cerr << "fitness1 < 0: " << fitness1 << std::endl;
183       fitness1 = 0;
184     }
185
186     fitness2 = rc > 1? (rss - rs*rs/rc) : 0;
187     if (fitness2 < 0) {
188       // std::cerr << "fitness2 < 0: " << fitness2 << std::endl;
189       fitness2 = 0;
190     }
191
192     double fitness = fitness0 + fitness1 + fitness2;
193
194     if (g_conf.feature_costs && g_conf.enable_feature_tunning) {
195       fitness *= g_conf.feature_costs[index];
196     }
197
198     if (*impurity > fitness) {
199       *impurity = fitness;
200       *value = (f1+f2)/2;
201       *gain = fitness00 - fitness1 - fitness2;
202     }
203   }
204
205   return *impurity != std::numeric_limits<double>::max();
206 }

计算impurity我的理解是应该计算全量样本的，代码的逻辑貌似是循环每一条非空特征的样本，然后取最小值。所以我的疑问是198-202行代码是不是应该在for循环之外呢，还是我的理解有问题？求解答

**Comment by PseudoProgrammer** [comment]
重新review了下代码，这种理解对吗？
计算impurity是全量样本，但全量样本分为了三部分计算再求和：1、fitness0是基于missing_value的样本算出。2、fitness1是基于fea_value<split_value的样本算出。3、fitness2是基于fea_value>split_value算出

**Comment by qiyiping** [comment]
你好，是的

**Comment by PseudoProgrammer** [comment]
好的，多谢！然后wikipead里基尼不纯度的计算方式是p(1-p)求和，代码里是p的方差。我的疑问是在选择特征分裂点时，是不是用的方差代替基尼不纯度
